---

# Scenario: all hosts fail
# Result: works as expected

- hosts: all
  become: true
  tasks:
    - debug: msg="start of test 2"

    - fail: msg="failure message"
      when: true

    - debug: msg="first debug message"

    - debug: msg="second debug message"

    - include: includes/include1.yml

    - debug: msg="final debug message"
